FROM ubuntu:18.04 as opensim-builder

RUN apt-get update \
 && apt-get install -y \
    curl \
    build-essential \
    git \
    cmake \
    swig3.0 \
    openjdk-8-jdk \
    liblapack-dev \
    libgconf-2-4 \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /tmp

# Download and extract OpenSim-Core.
RUN curl -sLO https://github.com/opensim-org/opensim-core/archive/4.1.tar.gz \
 && tar xzf 4.1.tar.gz \
 && rm 4.1.tar.gz

# Install Netbeans
RUN curl -sLO https://download.netbeans.org/netbeans/8.2/final/bundles/netbeans-8.2-javase-linux.sh \
 && chmod +x netbeans-8.2-javase-linux.sh \
 && ./netbeans-8.2-javase-linux.sh --silent \
 && rm netbeans-8.2-javase-linux.sh

# Download OpenSim-GUI.
RUN git clone https://github.com/opensim-org/opensim-gui.git \
 && cd opensim-gui \
 && git checkout 4.1 \
 && git submodule update --init --recursive -- opensim-models opensim-visualizer Gui/opensim/threejs

# Install OpenSim-Core dependencies.
RUN cd opensim-core-4.1 \
 && mkdir build-deps \
 && cd build-deps \
 && cmake ../dependencies \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX=/opt/opensim-deps \
 && make -j8

# Install OpenSim-Core.
RUN cd opensim-core-4.1 \
 && mkdir build \
 && cd build \
 && cmake .. \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX=/opt/opensim-core \
    -DOPENSIM_DEPENDENCIES_DIR=/opt/opensim-deps \
    -DOPENSIM_COPY_DEPENDENCIES=ON \
    -DBUILD_JAVA_WRAPPING=ON \
    -DWITH_BTK=ON \
    -DOPENSIM_INSTALL_UNIX_FHS=OFF \
 && make -j8 \
 && make install

# Install OpenSim-GUI.
RUN cd opensim-gui \
 && mkdir build \
 && cd build \
 && cmake .. \
    -DCMAKE_PREFIX_PATH=/opt/opensim-core \
    -DAnt_EXECUTABLE="/usr/local/netbeans-8.2/extide/ant/bin/ant" \
    -DANT_ARGS="-Dnbplatform.default.netbeans.dest.dir=/usr/local/netbeans-8.2;-Dnbplatform.default.harness.dir=/usr/local/netbeans-8.2/harness" \
 && make CopyOpenSimCore \
 && make CopyVisualizer \
 && make CopyModels

RUN make PrepareInstaller
RUN ls '/tmp/opensim-gui/Gui/opensim/' ; false

################################################################################

FROM ubuntu:18.04

# Create a non-root user and switch to it
RUN adduser --disabled-password --gecos '' --shell /bin/bash user
USER user

# All users can use /home/user as their home directory
ENV HOME=/home/user
RUN chmod 777 /home/user
WORKDIR /home/user

# # Copy OpenSim-Core into the image.
# COPY --from=opensim-builder /opt/opensim-core /opt/opensim-core
# RUN ls /opt/opensim-core

COPY --chown=user:user --from=opensim-builder /tmp/opensim-gui/Gui/opensim/dist/* /home/user/
RUN ls /home/user

# ENV OPENSIM_HOME=/opt/opensim-core \
#     LIBRARY_PATH=/opt/opensim-core/lib:$LIBRARY_PATH \
#     LD_LIBRARY_PATH=/opt/opensim-core/lib:$LD_LIBRARY_PATH \
#     PATH=/opt/opensim-core/bin:$PATH
